### ISSUE TITLE
Inconsistent as namespace (HTTP vs HTTPS)

### ISSUE THREAD

**Issue by tpluscode** [w3c/activitystreams#515] opened 2021-03-19 13:00 UTC
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [x] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

There is a discrepancy between the [JSON-LD and spec](https://github.com/w3c/activitystreams/blob/master/ns/activitystreams.jsonld#L5), which use `https` for the base namespace. This appears to be the correct.

The [vocabulary](https://github.com/w3c/activitystreams/blob/master/vocabulary/activitystreams2.owl#L2) however, has the `as` prefix declared using `http`

**Comment by nightpool** [comment] 2021-03-19 13:24
As I mentioned in your previous issue, the OWL vocabulary is non-normative and best effort, and is not maintained by the working group. It was contributed some time ago and I believe it is out of date in several respects, not only this one.

**Comment by csarven** [comment] 2021-03-24 08:27
This issue a duplicate of #515 and should be closed.

As for:

>not maintained by the working group

One way forward would be for the Social CG to address what's needed eg. https://github.com/w3c/activitystreams/pull/504#issuecomment-524551400 . Alternatively, have another group (possibly the Solid CG) or others to propose the updates to W3C.

**Closed** 2021-03-24 09:17 UTC
