### ISSUE TITLE
Media Type definition

### ISSUE THREAD

**Issue by dret** [w3c/activitystreams#53] opened 2014-11-13 09:38 UTC
in the media type registration http://www.w3.org/TR/activitystreams-core/#media-type, would it make sense to explicitly point out that the media type covers two "types" of documents, one being activity objects and one being collections? that would be the starting point for any implementer, right? request and/or get the media type, and then know what to expect.

**Comment by akuckartz** [comment] 2015-01-02 10:59
I still think that `application/ld+json` would be best because JSON-LD clients then do not need to consider additional media types. Maybe with a JSON-LD profile? /cc @lanthaler

**Comment by akuckartz** [comment] 2015-01-02 11:04
This issue seems to be a *duplicate* of #52

**Comment by jasnell** [comment] 2015-02-10 05:35
Yep, duplicate of #52

**Comment by dret** [comment] 2015-02-10 05:48
i wouldn't see this as a duplicate of #52, but they are certainly related.

**Comment by dret** [comment] 2015-02-10 05:57
for the record, i am not agreeing with closing this as a duplicate of #52. that's just not what this issue it is.

**Comment by jasnell** [comment] 2015-05-27 00:51
Closed given there's been no action or additional discussion

**Comment by dret** [comment] 2016-06-28 15:41
the possible action would have been to make the spec clearer that the AS2 media type defines to kinds of documents. if the WG decision is that no such clarification is needed, then i agree to closing this issue. i have read no argument, though, why clarifying this would not be an improvement of the spec language.

**Comment by rhiaro** [comment] 2016-06-28 19:21
@dret We discussed this on the call today and most of us think it's editorial, although @akuckartz says it's not, but possibly there's still some mix up between this issue and 52. If this is editorial, we can still make changes after/during CR. If you have time, it would be helpful if you could propose wording that would make this clearer for you.

But from the first couple of comments here, it looks like James disagrees with you about `Object`s and `Collection`s being different enough from each other to warrant documenting them as such. Each class and their relation to each other is discussed separately in [Model](https://www.w3.org/TR/activitystreams-core/#model). What would mentioning this in the Media Type section add?

We can put this on the agenda for next week's call (5th July) if you want to talk through. Pinging @evanp for further editor expertise.

**Comment by dret** [comment] 2016-06-29 07:10
hello amy.

On 2016-06-28 21:21, Amy Guy wrote:
> But from the first couple of comments here, it looks like James
> disagrees with you about |Object|s and |Collection|s being different
> enough from each other to warrant documenting them as such. Each class
> and their relation to each other is discussed separately in Model
> <https://www.w3.org/TR/activitystreams-core/#model>. What would
> mentioning this in the Media Type section add?

to me, the media type description is the route through which a developer 
will look at the spec. you look at the media type and try to figure out 
how it works. the very first question is: how many different "things" do 
i have to expect when using this media type? for AS2 the answer may be 
two (i think), and it would be useful to give this answer clearly and 
early on, rather than having it implicit in the "model" section.

but like i said, to me that's just an improvement suggestion from the 
spec writing perspective, and if the agreement is that this is not an 
improvement or not worth the effort, that's fine with me.

cheers,

dret.

-- 
erik wilde | mailto:erik.wilde@dret.net |
            | http://dret.net/netdret    |
            | http://twitter.com/dret    |

**Comment by evanp** [comment] 2016-07-05 17:19
I will resolve by calling out Collection as an important specific subtype of Object for this use.

**Closed** 2016-07-05 20:41 UTC
Labels: Commenter Satisfied
