### ISSUE TITLE
Some test files appear to be invalid

### ISSUE THREAD

**Issue by wezm** [w3c/activitystreams#420] opened 2017-05-06 06:23 UTC
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [x] Non-Blocking Issue

Please Describe the Issue:

Some of the [test files](https://github.com/w3c/activitystreams/tree/master/test) appear to be invalid:

## Missing type

[Section 3.1](https://www.w3.org/TR/activitypub/#obj-id) states:

> All objects have the following properties:
>
>* id
>    * The object's unique global identifier (unless the object is transient, in which case the id MAY be omitted). 
>* type
>    * The type of the object. 

* empty.json
* simple0001.json
* simple0002.json
* simple0003.json
* simple0004.json
* simple0005.json
* simple0006.json
* vocabulary-exid-jsonld.json

## Invalid JSON

* vocabulary-ex196-jsonld.json (multiline string for `content` needs newlines replaced with `\n`)

## map for name

Has a map for `name` property. Property should be `nameMap`.

* simple0011.json
* simple0012.json

**Comment by wezm** [comment] 2017-05-09 21:19
Ack just realised these test files are for ActivityStreams, not ActivityPub as I was assuming. That means the "Missing type" ones are probably valid Streams documents but not Pub.

**Comment by evanp** [comment] 2023-04-19 15:48
Since this was a issue made in error, and I believe the examples all validated correctly except for one which was intended as a counterexample, I'm going to close this issue.

**Closed by evanp** 2023-04-19 15:48 UTC
